print('===================================================================')
print('|  Scalar Type                                                    |')
print('|  1.int                                                          |')
print('|  2.float                                                        |')
print('|  4.None                                                         |')
print('|  5.bool                                                         |')
print("===================================================================\n\n")

print('01. int')
print('    1) string format    => Binary "0b1000" is %d' % 0b1000)
print('    2) format() method  => Binary "0b1001" is {0:1d}'.format(0b1001))
print('    3) bin() function   => bin(7) is' , bin(7))
print('    4) bin() function   => bin(0o11) is', bin(0o11))
print('    5) bin() function   => bin(0xf) is', bin(0xf), end='\n\n')

print('    1) string format    => Octa "0o11" is %d' % 0o11)
print('    2) format() method  => Octa "0o12" is {0:1d}'.format(0o12))
print('    3) oct() function   => oct(7) is' , oct(7))
print('    4) oct() function   => oct(0b11) is', oct(0b11))
print('    5) oct() function   => oct(0xf) is', oct(0xf), end='\n\n')

print('    1) string format    => Hex "0x1e" is %d' % 0x1e)
print('    2) format() method  => Hex "0x1f" is {0:1d}'.format(0x1f))
print('    3) hex() function   => hex(7) is' , hex(7))
print('    4) hex() function   => hex(0b11) is', hex(0b11))
print('    5) hex() function   => hex(0o17) is', hex(0o17), end='\n\n')

print('02. float')
print('    1) The result of "3e+8" is', 3e+8)
print('    2) The result of "1.672e+2" is', 1.672e+2)
print('    3) The result of "1.616e-10" is', 1.616e-10)
print('    4) The result of float(7) is', float(7))
print('    5) The yield is {0:2.2f}%'.format(145/153*100))
print('    6) The yield is %2.2f%%' % (145/153*100))
print('    7) The result of float(1.618) is', float(1.618), end='\n\n')

print('03. None')
a = None
print('    1) a is', a)
print('    2) The result of "a is None" is', a is None, end='\n\n')

print('04. bool')
print('    1) The result of bool(0) is', bool(0)) 
print('    2) The result of bool(1) is', bool(1))
print('    3) The result of bool(-1) is', bool(-1))
print('    4) The result of bool("") is', bool(""))
print('    5) The result of bool("abc") is', bool("abc"))
print('    6) The result of bool([]) is', bool([]))
print('    7) The result of bool([0]) is', bool([0]))
print('    8) The result of bool({"a":0}) is', bool({"a":0}))
print('    9) The result of 3 == 4 is', 3 == 4)
